/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
parameters: {'combined_datasets': 'yelp_polarity---amazon_polarity', 'shuffle': True, 'chunk_size': 2048, 'num_embedding_features': 100, 'test_interval': 1000, 'test_only': 0, 'maxlen': 1024, 'gpu': True, 'seed': 1337, 'joint_ratio': 0.5, 'depth': 29, 'model_load_path': 'models/VDCNN/VDCNN_yelp_polarity---amazon_polarity_depth@29/50/best_model.pt', 'lr_halve_interval': 15000.0, 'iterations': 50000, 'test_batch_size': 128, 'joint_training': True, 'model_folder': 'models/VDCNN/VDCNN_yelp_polarity---amazon_polarity_depth@29/50', 'model_save_path': 'models/VDCNN/VDCNN_yelp_polarity---amazon_polarity_depth@29/50', 'lr': 0.01, 'shortcut': False, 'last_pooling_layer': 'k-max-pooling', 'class_weights': None, 'dataset': 'yelp_polarity', 'joint_test': 0, 'batch_size': 128, 'test_dataset': 'amazon_polarity'}
Joint Training !
dataset: YelpPolarity, n_classes: 2
  - loading dataset...
dataset: AmazonPolarity, n_classes: 2
  - loading dataset...
Both datasets loaded, going to mix ...
  - txt vectorization...
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 382, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 324, in joint_train
    logger.info("Number of classes in the mixed dataset are: ", n_classes, type(n_classes))
Message: 'Number of classes in the mixed dataset are: '
Arguments: (4, <class 'int'>)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 382, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 324, in joint_train
    logger.info("Number of classes in the mixed dataset are: ", n_classes, type(n_classes))
Message: 'Number of classes in the mixed dataset are: '
Arguments: (4, <class 'int'>)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 382, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 327, in joint_train
    logger.info("Seed for random numbers: ", torch.initial_seed())
Message: 'Seed for random numbers: '
Arguments: (1337,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 382, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 327, in joint_train
    logger.info("Seed for random numbers: ", torch.initial_seed())
Message: 'Seed for random numbers: '
Arguments: (1337,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 382, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 330, in joint_train
    logger.info("Overriding the number of embedding features to: ", n_txt_feats)
Message: 'Overriding the number of embedding features to: '
Arguments: (100,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 382, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 330, in joint_train
    logger.info("Overriding the number of embedding features to: ", n_txt_feats)
Message: 'Overriding the number of embedding features to: '
Arguments: (100,)
Joint training
Mixed_yelp_polarity---amazon_polarity_0.5 - Iter [0/50000] - train metrics: {'accuracy': 0.6640625, 'logloss': -1}
/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py:77: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  yhat = nn.functional.softmax(yhat)
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 382, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 354, in joint_train
    train(opt, model, criterion, tr_data, te_data, n_classes, dataset_name)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 249, in train
    y_prob = predict_from_model(te_gen, model, gpu=opt.gpu)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 74, in predict_from_model
    yhat = model(tdata[0])
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 204, in forward
    out = self.layers(out)
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 117, in forward
    out = self.conv2(out)
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 166, in forward
    self.padding, self.dilation, self.groups)
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 54, in conv1d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR
